# {{.RENDER_MSG}}
# SOURCE: {{.SRC}}
ARG ARCH
ARG OS

# {{.GO_IMG}}
FROM --platform=linux/${ARCH} {{.GO_PIN}} AS go

FROM go AS fluent-bit-plugin
ARG VERSION
ENV GOEXPERIMENT=systemcrypto
WORKDIR /cilium-log-collector
COPY ./cilium-log-collector .
RUN go build -buildmode=c-shared -a -o out_azure_app_insights.so -trimpath -ldflags "-X main.version=$VERSION" -gcflags="-dwarflocationlists=true" .

FROM mcr.microsoft.com/oss/v2/fluent/fluent-bit:v4.2.3-16 as linux
COPY --from=fluent-bit-plugin /cilium-log-collector/out_azure_app_insights.so /out_azure_app_insights.so
